from __future__ import annotations

import math
import os
import secrets
import sqlite3
from datetime import date, datetime, timedelta
from functools import wraps
from pathlib import Path
from typing import Any, Dict, List

import requests
from flask import Flask, flash, g, jsonify, redirect, render_template, request, session, url_for

try:
    from dotenv import load_dotenv
except ImportError:
    load_dotenv = None

if load_dotenv:
    load_dotenv()


BASE_DIR = Path(__file__).resolve().parent
DEFAULT_DB_PATH = BASE_DIR / "data" / "journal.db"

app = Flask(__name__)
app.config["SECRET_KEY"] = os.environ.get("JOURNAL_SECRET", "dev-key-change-me")
app.config["SUPABASE_URL"] = os.environ.get("SUPABASE_URL", "").strip()
app.config["SUPABASE_ANON_KEY"] = os.environ.get("SUPABASE_ANON_KEY", "").strip()
app.config["SUPABASE_DB_URL"] = os.environ.get("SUPABASE_DB_URL", "").strip()
app.config["DATABASE_URL"] = os.environ.get("DATABASE_URL", "").strip()
app.config["INVITE_TTL_DAYS"] = int(os.environ.get("INVITE_TTL_DAYS", "7"))

ADMIN_EMAILS = {
    value.strip().lower()
    for value in os.environ.get("ADMIN_EMAILS", "").split(",")
    if value.strip()
}

app.config["DB_ENGINE"] = "postgres" if app.config["SUPABASE_DB_URL"] or app.config["DATABASE_URL"] else "sqlite"

if app.config["DB_ENGINE"] == "postgres":
    app.config["DATABASE"] = app.config["SUPABASE_DB_URL"] or app.config["DATABASE_URL"]
else:
    app.config["DATABASE"] = Path(os.environ.get("JOURNAL_DB_PATH", str(DEFAULT_DB_PATH)))
    if os.environ.get("VERCEL") and "JOURNAL_DB_PATH" not in os.environ:
        app.config["DATABASE"] = Path("/tmp/journal.db")

DEFAULT_STUDENTS = [
    "Andreev",
    "Gavrikov",
    "Gordeev",
    "Grishin",
    "Emelyanova",
    "Zhukov",
    "Imomdodov",
    "Iskanderova",
    "Kozirev",
    "Krasnobaev",
    "Maslova",
    "Osipov",
    "Polozova",
    "Pryahin",
    "Razzhivin",
    "Romanova",
    "Ryabkov",
    "Snegur",
    "Tihomirov",
    "Tkachenko",
    "Trubitsa",
    "Haliev",
    "Sheshin",
    "Sherbaev",
]


def now_iso() -> str:
    return datetime.utcnow().replace(microsecond=0).isoformat() + "Z"


def is_postgres() -> bool:
    return app.config.get("DB_ENGINE") == "postgres"


def adapt_sql(sql: str) -> str:
    return sql.replace("?", "%s") if is_postgres() else sql


def configure_connection(conn: sqlite3.Connection) -> None:
    if is_postgres():
        return
    conn.execute("PRAGMA foreign_keys = ON")
    conn.execute("PRAGMA journal_mode = WAL")
    conn.execute("PRAGMA synchronous = NORMAL")
    conn.execute("PRAGMA busy_timeout = 3000")


def ensure_schema() -> None:
    if is_postgres():
        import psycopg2

        conn = psycopg2.connect(app.config["DATABASE"])
        schema_sql = """
        CREATE TABLE IF NOT EXISTS students (
            student_id TEXT PRIMARY KEY,
            name TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS grades (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            student_id TEXT NOT NULL,
            subject TEXT NOT NULL,
            grade REAL NOT NULL,
            date TEXT NOT NULL,
            note TEXT,
            FOREIGN KEY(student_id) REFERENCES students(student_id) ON DELETE CASCADE
        );

        CREATE INDEX IF NOT EXISTS idx_grades_student_date
            ON grades(student_id, date);

        CREATE TABLE IF NOT EXISTS attendance (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            student_id TEXT NOT NULL,
            date TEXT NOT NULL,
            present INTEGER NOT NULL CHECK(present IN (0, 1)),
            note TEXT,
            FOREIGN KEY(student_id) REFERENCES students(student_id) ON DELETE CASCADE
        );

        CREATE INDEX IF NOT EXISTS idx_attendance_student_date
            ON attendance(student_id, date);

        CREATE TABLE IF NOT EXISTS users (
            id TEXT PRIMARY KEY,
            email TEXT NOT NULL,
            role TEXT NOT NULL DEFAULT 'user',
            created_at TEXT NOT NULL,
            last_seen TEXT NOT NULL
        );

        CREATE INDEX IF NOT EXISTS idx_users_role
            ON users(role);

        CREATE TABLE IF NOT EXISTS admin_invites (
            token TEXT PRIMARY KEY,
            created_at TEXT NOT NULL,
            expires_at TEXT,
            used_by TEXT,
            used_at TEXT
        );
        """
        with conn:
            with conn.cursor() as cur:
                cur.execute(schema_sql)
        conn.close()
        return

    db_path: Path = app.config["DATABASE"]
    db_path.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(db_path)
    configure_connection(conn)
    conn.executescript(
        """
        CREATE TABLE IF NOT EXISTS students (
            student_id TEXT PRIMARY KEY,
            name TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS grades (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            student_id TEXT NOT NULL,
            subject TEXT NOT NULL,
            grade REAL NOT NULL,
            date TEXT NOT NULL,
            note TEXT,
            FOREIGN KEY(student_id) REFERENCES students(student_id) ON DELETE CASCADE
        );

        CREATE INDEX IF NOT EXISTS idx_grades_student_date
            ON grades(student_id, date);

        CREATE TABLE IF NOT EXISTS attendance (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            student_id TEXT NOT NULL,
            date TEXT NOT NULL,
            present INTEGER NOT NULL CHECK(present IN (0, 1)),
            note TEXT,
            FOREIGN KEY(student_id) REFERENCES students(student_id) ON DELETE CASCADE
        );

        CREATE INDEX IF NOT EXISTS idx_attendance_student_date
            ON attendance(student_id, date);

        CREATE TABLE IF NOT EXISTS users (
            id TEXT PRIMARY KEY,
            email TEXT NOT NULL,
            role TEXT NOT NULL DEFAULT 'user',
            created_at TEXT NOT NULL,
            last_seen TEXT NOT NULL
        );

        CREATE INDEX IF NOT EXISTS idx_users_role
            ON users(role);

        CREATE TABLE IF NOT EXISTS admin_invites (
            token TEXT PRIMARY KEY,
            created_at TEXT NOT NULL,
            expires_at TEXT,
            used_by TEXT,
            used_at TEXT
        );
        """
    )
    conn.commit()
    conn.close()


def get_db():
    if "db" not in g:
        if is_postgres():
            import psycopg2
            from psycopg2.extras import RealDictCursor

            conn = psycopg2.connect(app.config["DATABASE"])
            conn.autocommit = False
            g.db = conn
            g.db_cursor_factory = RealDictCursor
        else:
            db = sqlite3.connect(app.config["DATABASE"], detect_types=sqlite3.PARSE_DECLTYPES)
            db.row_factory = sqlite3.Row
            configure_connection(db)
            g.db = db
    return g.db


def db_fetchall(sql: str, params: tuple = ()) -> List[Dict[str, Any]]:
    conn = get_db()
    sql = adapt_sql(sql)
    if is_postgres():
        cursor_factory = g.get("db_cursor_factory")
        with conn.cursor(cursor_factory=cursor_factory) as cur:
            cur.execute(sql, params)
            rows = cur.fetchall()
        return [dict(row) for row in rows]
    rows = conn.execute(sql, params).fetchall()
    return [dict(row) for row in rows]


def db_fetchone(sql: str, params: tuple = ()) -> Dict[str, Any] | None:
    conn = get_db()
    sql = adapt_sql(sql)
    if is_postgres():
        cursor_factory = g.get("db_cursor_factory")
        with conn.cursor(cursor_factory=cursor_factory) as cur:
            cur.execute(sql, params)
            row = cur.fetchone()
        return dict(row) if row else None
    row = conn.execute(sql, params).fetchone()
    return dict(row) if row else None


def db_execute(sql: str, params: tuple = ()) -> None:
    conn = get_db()
    sql = adapt_sql(sql)
    if is_postgres():
        with conn.cursor() as cur:
            cur.execute(sql, params)
    else:
        conn.execute(sql, params)
    conn.commit()


def db_executemany(sql: str, params: list[tuple]) -> None:
    conn = get_db()
    sql = adapt_sql(sql)
    if is_postgres():
        with conn.cursor() as cur:
            cur.executemany(sql, params)
    else:
        conn.executemany(sql, params)
    conn.commit()


@app.teardown_appcontext
def close_db(exception: Exception | None = None) -> None:
    db = g.pop("db", None)
    if db is not None:
        db.close()


def fetch_supabase_user(access_token: str) -> Dict[str, Any] | None:
    supabase_url = app.config["SUPABASE_URL"]
    supabase_key = app.config["SUPABASE_ANON_KEY"]
    if not supabase_url or not supabase_key or not access_token:
        return None
    url = f"{supabase_url.rstrip('/')}/auth/v1/user"
    try:
        response = requests.get(
            url,
            headers={
                "Authorization": f"Bearer {access_token}",
                "apikey": supabase_key,
            },
            timeout=6,
        )
    except requests.RequestException:
        return None
    if response.status_code != 200:
        return None
    try:
        return response.json()
    except ValueError:
        return None


def upsert_user(user_id: str, email: str) -> str:
    now = now_iso()
    row = db_fetchone("SELECT role FROM users WHERE id = ?", (user_id,))
    if row:
        role = row["role"]
        db_execute(
            "UPDATE users SET email = ?, last_seen = ? WHERE id = ?",
            (email, now, user_id),
        )
    else:
        role = "admin" if email.lower() in ADMIN_EMAILS else "user"
        db_execute(
            "INSERT INTO users (id, email, role, created_at, last_seen) VALUES (?, ?, ?, ?, ?)",
            (user_id, email, role, now, now),
        )
    return role


def list_users() -> List[Dict[str, Any]]:
    return db_fetchall(
        "SELECT id, email, role, created_at, last_seen FROM users ORDER BY created_at DESC"
    )


def list_invites() -> List[Dict[str, Any]]:
    return db_fetchall(
        """
        SELECT token, created_at, expires_at, used_by, used_at
        FROM admin_invites
        ORDER BY created_at DESC
        """
    )


def create_invite() -> str:
    token = secrets.token_urlsafe(24)
    now = now_iso()
    ttl_days = app.config.get("INVITE_TTL_DAYS", 7)
    expires_at = (datetime.utcnow() + timedelta(days=ttl_days)).replace(microsecond=0).isoformat() + "Z"
    db_execute(
        "INSERT INTO admin_invites (token, created_at, expires_at) VALUES (?, ?, ?)",
        (token, now, expires_at),
    )
    return token


def login_required(view):
    @wraps(view)
    def wrapper(*args, **kwargs):
        if not session.get("user_id"):
            return redirect(url_for("login"))
        return view(*args, **kwargs)

    return wrapper


def admin_required(view):
    @wraps(view)
    def wrapper(*args, **kwargs):
        if not session.get("user_id"):
            return redirect(url_for("login"))
        if session.get("role") != "admin":
            return redirect(url_for("pending"))
        return view(*args, **kwargs)

    return wrapper


@app.context_processor
def inject_globals() -> Dict[str, Any]:
    return {
        "current_user": {
            "email": session.get("email"),
            "role": session.get("role"),
        }
        if session.get("user_id")
        else None,
        "is_admin": session.get("role") == "admin",
        "supabase_url": app.config["SUPABASE_URL"],
        "supabase_anon_key": app.config["SUPABASE_ANON_KEY"],
    }


def seed_students_if_empty() -> None:
    row = db_fetchone("SELECT 1 AS exists_flag FROM students LIMIT 1")
    if row:
        return
    payload = []
    for idx, name in enumerate(DEFAULT_STUDENTS, start=1):
        student_id = f"S{idx:03d}"
        payload.append((student_id, name))
    db_executemany("INSERT INTO students (student_id, name) VALUES (?, ?)", payload)



def fetch_summary() -> List[Dict[str, Any]]:
    rows = db_fetchall(
        """
        SELECT s.student_id,
               s.name,
               g.avg_grade,
               g.grades_count,
               a.attendance_rate,
               a.attendance_count
        FROM students s
        LEFT JOIN (
            SELECT student_id,
                   AVG(grade) AS avg_grade,
                   COUNT(*) AS grades_count
            FROM grades
            GROUP BY student_id
        ) g ON g.student_id = s.student_id
        LEFT JOIN (
            SELECT student_id,
                   AVG(CASE WHEN present = 1 THEN 1.0 ELSE 0.0 END) AS attendance_rate,
                   COUNT(*) AS attendance_count
            FROM attendance
            GROUP BY student_id
        ) a ON a.student_id = s.student_id
        ORDER BY s.student_id;
        """
    )

    summary: List[Dict[str, Any]] = []
    for row in rows:
        summary.append(
            {
                "student_id": row["student_id"],
                "name": row["name"],
                "average_grade": round(float(row["avg_grade"] or 0.0), 2),
                "grades_count": int(row["grades_count"] or 0),
                "attendance_rate": round(float(row["attendance_rate"] or 0.0) * 100, 2),
                "attendance_count": int(row["attendance_count"] or 0),
            }
        )
    return summary


def fetch_class_stats() -> Dict[str, Any]:
    row = db_fetchone("SELECT COUNT(*) AS count FROM students")
    students_count = int(row["count"] if row else 0)
    grade_row = db_fetchone(
        "SELECT AVG(grade) AS avg_grade, COUNT(*) AS grades_count FROM grades"
    )
    attendance_row = db_fetchone(
        """
        SELECT AVG(CASE WHEN present = 1 THEN 1.0 ELSE 0.0 END) AS attendance_rate,
               COUNT(*) AS attendance_count
        FROM attendance
        """
    )

    return {
        "students_count": students_count,
        "average_grade": round(float((grade_row or {}).get("avg_grade") or 0.0), 2),
        "grades_count": int((grade_row or {}).get("grades_count") or 0),
        "attendance_rate": round(float((attendance_row or {}).get("attendance_rate") or 0.0) * 100, 2),
        "attendance_count": int((attendance_row or {}).get("attendance_count") or 0),
    }


def get_student(student_id: str) -> Dict[str, Any] | None:
    return db_fetchone(
        "SELECT student_id, name FROM students WHERE student_id = ?",
        (student_id,),
    )


def get_student_stats(student_id: str) -> Dict[str, Any]:
    grade_row = db_fetchone(
        "SELECT AVG(grade) AS avg_grade, COUNT(*) AS grades_count FROM grades WHERE student_id = ?",
        (student_id,),
    )
    attendance_row = db_fetchone(
        """
        SELECT AVG(CASE WHEN present = 1 THEN 1.0 ELSE 0.0 END) AS attendance_rate,
               COUNT(*) AS attendance_count
        FROM attendance
        WHERE student_id = ?
        """,
        (student_id,),
    )
    return {
        "average_grade": round(float((grade_row or {}).get("avg_grade") or 0.0), 2),
        "grades_count": int((grade_row or {}).get("grades_count") or 0),
        "attendance_rate": round(float((attendance_row or {}).get("attendance_rate") or 0.0) * 100, 2),
        "attendance_count": int((attendance_row or {}).get("attendance_count") or 0),
    }


@app.get("/login")
def login() -> str:
    return render_template("login.html", today=date.today().isoformat())


@app.post("/auth/session")
def auth_session() -> tuple[str, int] | tuple[Dict[str, Any], int]:
    payload = request.get_json(silent=True) or {}
    access_token = (payload.get("access_token") or "").strip()
    if not access_token:
        return jsonify({"error": "missing_token"}), 400

    user = fetch_supabase_user(access_token)
    if not user or not user.get("id"):
        return jsonify({"error": "invalid_token"}), 401

    email = user.get("email") or ""
    role = upsert_user(user["id"], email)
    session["user_id"] = user["id"]
    session["email"] = email
    session["role"] = role
    session.permanent = True
    redirect_url = url_for("index") if role == "admin" else url_for("pending")
    return jsonify({"ok": True, "role": role, "redirect": redirect_url}), 200


@app.get("/logout")
def logout() -> str:
    session.clear()
    return redirect(url_for("login"))


@app.get("/pending")
@login_required
def pending() -> str:
    return render_template("pending.html", today=date.today().isoformat())


@app.get("/invite/<token>")
@login_required
def accept_invite(token: str) -> str:
    row = db_fetchone(
        "SELECT token, expires_at, used_at FROM admin_invites WHERE token = ?",
        (token,),
    )
    if not row:
        flash("Инвайт не найден.", "error")
        return redirect(url_for("pending"))
    if row["used_at"]:
        flash("Инвайт уже использован.", "error")
        return redirect(url_for("pending"))
    expires_at = row["expires_at"]
    if expires_at and expires_at < now_iso():
        flash("Инвайт истёк.", "error")
        return redirect(url_for("pending"))

    user_id = session.get("user_id")
    if not user_id:
        return redirect(url_for("login"))

    db_execute("UPDATE users SET role = 'admin' WHERE id = ?", (user_id,))
    db_execute(
        "UPDATE admin_invites SET used_by = ?, used_at = ? WHERE token = ?",
        (user_id, now_iso(), token),
    )
    session["role"] = "admin"
    flash("Доступ учителя активирован.", "success")
    return redirect(url_for("index"))


@app.get("/admin")
@admin_required
def admin_panel() -> str:
    users = list_users()
    invites = list_invites()
    return render_template(
        "admin.html",
        users=users,
        invites=invites,
        today=date.today().isoformat(),
    )


@app.post("/admin/invites")
@admin_required
def create_invite_route() -> str:
    token = create_invite()
    flash(f"Инвайт создан: {request.url_root}invite/{token}", "success")
    return redirect(url_for("admin_panel"))


@app.route("/")
@admin_required
def index() -> str:
    students = fetch_summary()
    class_stats = fetch_class_stats()
    return render_template(
        "index.html",
        students=students,
        class_stats=class_stats,
        today=date.today().isoformat(),
    )


@app.post("/students")
@admin_required
def add_student() -> str:
    student_id = (request.form.get("student_id") or "").strip()
    name = (request.form.get("name") or "").strip()

    if not student_id or not name:
        flash("Укажите ID и имя ученика.", "error")
        return redirect(url_for("index"))

    try:
        db_execute(
            "INSERT INTO students (student_id, name) VALUES (?, ?)",
            (student_id, name),
        )
        flash("Ученик добавлен.", "success")
    except Exception:
        flash("Ученик с таким ID уже существует.", "error")

    return redirect(url_for("index"))


@app.route("/students/<student_id>")
@admin_required
def student_detail(student_id: str) -> str:
    student = get_student(student_id)
    if not student:
        flash("Ученик не найден.", "error")
        return redirect(url_for("index"))

    grades = db_fetchall(
        """
        SELECT id, subject, grade, date, note
        FROM grades
        WHERE student_id = ?
        ORDER BY date DESC, id DESC
        """,
        (student_id,),
    )
    attendance = db_fetchall(
        """
        SELECT id, date, present, note
        FROM attendance
        WHERE student_id = ?
        ORDER BY date DESC, id DESC
        """,
        (student_id,),
    )
    subjects = db_fetchall(
        """
        SELECT subject, ROUND(AVG(grade), 2) AS average, COUNT(*) AS count
        FROM grades
        WHERE student_id = ?
        GROUP BY subject
        ORDER BY subject
        """,
        (student_id,),
    )

    stats = get_student_stats(student_id)

    return render_template(
        "student.html",
        student=student,
        grades=grades,
        attendance=attendance,
        subjects=subjects,
        stats=stats,
        today=date.today().isoformat(),
    )


@app.post("/students/<student_id>/grades")
@admin_required
def add_grade(student_id: str) -> str:
    student = get_student(student_id)
    if not student:
        flash("Ученик не найден.", "error")
        return redirect(url_for("index"))

    subject = (request.form.get("subject") or "").strip()
    grade_raw = (request.form.get("grade") or "").strip()
    entry_date = (request.form.get("date") or date.today().isoformat()).strip()
    note = (request.form.get("note") or "").strip() or None

    if not subject or not grade_raw:
        flash("Укажите предмет и оценку.", "error")
        return redirect(url_for("student_detail", student_id=student_id))

    try:
        grade_value = float(grade_raw.replace(",", "."))
    except ValueError:
        flash("Оценка должна быть числом.", "error")
        return redirect(url_for("student_detail", student_id=student_id))

    if not math.isfinite(grade_value):
        flash("Оценка должна быть конечным числом.", "error")
        return redirect(url_for("student_detail", student_id=student_id))

    db_execute(
        "INSERT INTO grades (student_id, subject, grade, date, note) VALUES (?, ?, ?, ?, ?)",
        (student_id, subject, grade_value, entry_date, note),
    )
    flash("Оценка добавлена.", "success")
    return redirect(url_for("student_detail", student_id=student_id))


@app.post("/students/<student_id>/attendance")
@admin_required
def add_attendance(student_id: str) -> str:
    student = get_student(student_id)
    if not student:
        flash("Ученик не найден.", "error")
        return redirect(url_for("index"))

    entry_date = (request.form.get("date") or date.today().isoformat()).strip()
    present_raw = request.form.get("present")
    note = (request.form.get("note") or "").strip() or None

    if present_raw not in {"1", "0"}:
        flash("Выберите статус посещаемости.", "error")
        return redirect(url_for("student_detail", student_id=student_id))

    db_execute(
        "INSERT INTO attendance (student_id, date, present, note) VALUES (?, ?, ?, ?)",
        (student_id, entry_date, int(present_raw), note),
    )
    flash("Посещаемость отмечена.", "success")
    return redirect(url_for("student_detail", student_id=student_id))


ensure_schema()
seed_students_if_empty()


if __name__ == "__main__":
    app.run(debug=True)
